eShopSolution.AdminApp/Controllers/Components/PagerViewComponent.cs
using eShopSolution.ViewModel.Common;
using Microsoft.AspNetCore.Mvc;

namespace eShopSolution.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

eShopSolution.AdminApp/Controllers/LoginController.cs
using eShopSolution.ViewModel.System.User;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using eShopSolution.AdminApp.Services.User;
using Microsoft.AspNetCore.Identity;
using eShopSolution.Data.Entities;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Owin.Security;
using NuGet.Protocol.Plugins;
using AutoMapper;
using Microsoft.AspNetCore.Authentication.Google;
using System.Web;

namespace eShopSolution.AdminApp.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {

        private readonly IUserApiService _userApiService;
        private readonly IConfiguration _configuration;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly IMapper _mapper;

        public LoginController(IMapper mapper ,IUserApiService userApiService, IConfiguration configuration, SignInManager<AppUser> sigInManager, UserManager<AppUser> userManager)
        {
            _userApiService = userApiService;
            _configuration = configuration;
            _signInManager = sigInManager;
            _userManager = userManager;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }




        [HttpPost]
        public async Task<IActionResult> Inzdex(LoginUserRequest request)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Error = "Incorrect Email or password";
                return View();
            }
            var apiResult = await _userApiService.Authenticate(request);

            if (apiResult.IsSuccessed)
            {
                var userPrincipal = this.ValidateToken(apiResult.ResultObj);
                var authProperties = new Microsoft.AspNetCore.Authentication.AuthenticationProperties
                {
                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                    IsPersistent = false
                };
                HttpContext.Session.SetString("token", apiResult.ResultObj);
                await HttpContext.SignInAsync(
                            CookieAuthenticationDefaults.AuthenticationScheme,
                            userPrincipal,
                            authProperties);

                return RedirectToAction("Index", "Home");
            }
            ViewBag.Error = "Incorrect Email or password";
            return View();
        }

        private ClaimsPrincipal ValidateToken(string jwtToken)
        {
            IdentityModelEventSource.ShowPII = true;

            SecurityToken validatedToken;
            TokenValidationParameters validationParameters = new TokenValidationParameters();

            validationParameters.ValidateLifetime = true;

            validationParameters.ValidAudience = _configuration["Jwt:Audience"];
            validationParameters.ValidIssuer = _configuration["Jwt:Issuer"];
            validationParameters.IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Jwt:Key"]));

            ClaimsPrincipal principal = new JwtSecurityTokenHandler().ValidateToken(jwtToken, validationParameters, out validatedToken);

            return principal;
        }

        [AllowAnonymous]
        public IActionResult GoogleLogin(string provider)
        {
            string redirectUrl = Url.Action("GoogleLoginResponse", "Login");
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            var result = new ChallengeResult(provider, properties);
            return result;
        }
            
        [AllowAnonymous]
        public async Task<IActionResult> GoogleLoginResponse()
        {
            ExternalLoginInfo info = await _signInManager.GetExternalLoginInfoAsync();  
            if (info == null)
            {
                return RedirectToAction("LoginPortal");
            }
            else
            {
                var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    AppUser user = null;
                    if (info.LoginProvider == "Facebook")
                    {
                        Random rd = new Random();
                        string prefix = "FB"+ rd.Next(0,9).ToString() + rd.Next(0,9).ToString() + rd.Next(0,9).ToString() + rd.Next(0, 9).ToString() + rd.Next(0, 9).ToString() + rd.Next(0, 9).ToString() ;
                        string username = prefix;
                         user = new AppUser()
                        {
                            FirstName = info.Principal.FindFirst(ClaimTypes.GivenName)?.Value,
                            LastName = info.Principal.FindFirst(ClaimTypes.Surname)?.Value,
                            Email = info.Principal.FindFirst(ClaimTypes.Email)?.Value,
                        };
                    }

                    if (info.LoginProvider == "Google")
                    {
                        Random rd = new Random();
                        string prefix = "GG" + rd.Next(0, 9).ToString() + rd.Next(0, 9).ToString() + rd.Next(0, 9).ToString() + rd.Next(0, 9).ToString() + rd.Next(0, 9).ToString() + rd.Next(0, 9).ToString();
                        string username = prefix;


                        user = new AppUser()
                        {
                            FirstName = info.Principal.FindFirst(ClaimTypes.GivenName)?.Value,
                            LastName = info.Principal.FindFirst(ClaimTypes.Surname)?.Value, // Example: Surname claim
                            Email = info.Principal.FindFirst(ClaimTypes.Email)?.Value,
                            UserName = username,
                        };
                    }

                   
                    
                    var createUserResult = await _userManager.CreateAsync(user);

                    if (createUserResult.Succeeded)
                    {
                        var identResult = await _userManager.AddLoginAsync(user, info);
                        if (identResult.Succeeded)
                        {
                            await _signInManager.SignInAsync(user, false);
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
            }
            return View();
        }



    }
}

eShopSolution.AdminApp/Controllers/UserController.cs
using eShopSolution.ViewModel.System.User;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using eShopSolution.Utilities;
using Microsoft.AspNetCore.Authorization;
using eShopSolution.ViewModel.Common;
using Microsoft.AspNetCore.Identity;
using eShopSolution.Data.Enums;
using eShopSolution.AdminApp.Services.User;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using eShopSolution.Data.Entities;
using eShopSolution.AdminApp.Services.Role;
using eShopSolution.ViewModel.System.Role;
using eShopSolution.AdminApp.Models;
using PayPal.Api;

namespace eShopSolution.AdminApp.Controllers
{


    public class UserController : BaseController
    {
        private readonly IUserApiService _userApiService;
        private readonly IConfiguration _configuration;
        private readonly IRoleApiService _roleApiService;

        public UserController(IUserApiService userApiService, IConfiguration configuration, IRoleApiService roleApiService)
        {
            _userApiService = userApiService;
            _configuration = configuration;
            _roleApiService = roleApiService;
        }
        [HttpGet]
        public async Task<IActionResult> Register()
        {
            
            ViewBag.ListRole = _roleApiService.GetRolesForView().Result.ResultObj.ToList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterUserRequest request)
        {
            var status = await _userApiService.Register(request);

            ViewBag.ListRole = _roleApiService.GetRolesForView().Result.ResultObj.ToList();

            if (status is ApiErrorResult<IdentityResult> errorResult)
            {
                ViewBag.Errors = errorResult.ValidationErrors;
                return View();
            }
            TempData["SuccessMsg"] = "Create success for Username " + request.UserName;

            return RedirectToAction("GetAllUser", "User");
        }





        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("token");
            return RedirectToAction("Index", "Login");
        }


        [HttpGet]
        public async Task<IActionResult> GetAllUser(ViewListUserPagingRequest request)
        {

            try
            {
                ViewBag.txtLastSeachValue = request.Keyword;
                if (!ModelState.IsValid)
                {
                    return View();
                }
                if (TempData["FailMsg"] != null)
                {
                    ViewBag.FailMsg = TempData["FailMsg"];
                }
                if (TempData["SuccessMsg"] != null)
                {
                    ViewBag.SuccessMsg = TempData["SuccessMsg"];
                }
                var listUser = await _userApiService.GetAllUser(request);
                return View(listUser.ResultObj);
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid UserId)
        {
            try
            {
                ViewBag.ListRole = _roleApiService.GetRolesForView().Result.ResultObj.ToList();

                if (!ModelState.IsValid)
                {
                    return View();
                }

                var User = await _userApiService.GetUserById(UserId);
                return View(User.ResultObj);
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserRequest request)
        {
            try
            {
                ViewBag.ListRole = _roleApiService.GetRolesForView().Result.ResultObj.ToList();


                if (!ModelState.IsValid)
                {
                    return View();
                }
                var status = await _userApiService.Edit(request);
                if (status is ApiErrorResult<bool> errorResult)
                {
                    ViewBag.Errors = errorResult.ValidationErrors;
                    return View();
                }
                TempData["SuccessMsg"] = "Edit success for Username with phoneNumber " + request.PhoneNumber;
                return RedirectToAction("GetAllUser", "User");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detail(ViewDetailUserRequest request)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    return View();
                }
                var status = await _userApiService.Detail(request);
                if (status is ApiErrorResult<UserViewModel> errorResult)
                {
                    ViewBag.Error = "Cannot get this userId " + request.UserId.ToString();
                    return View();
                }
                return View(status.ResultObj);
            }
            catch
            {
                return View();
            }
        }


        [HttpGet]
        public async Task<IActionResult> Delete(Guid UserId)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    return View();
                }

                var User = await _userApiService.GetUserById(UserId);
                return View(User.ResultObj);
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteUserRequest request)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    return View();
                }
                var status = await _userApiService.Delete(request);
                if (status is ApiErrorResult<bool> errorResult)
                {
                    ViewBag.Errors = errorResult.ValidationErrors;
                    return View();
                }
                TempData["SuccessMsg"] = "Delete success UserId " + request.Id;
                return RedirectToAction("GetAllUser", "User");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Forbidden()
        {
            return View();
        }



    }


}

eShopSolution.AdminApp/Views/User/Delete.cshtml
@model eShopSolution.ViewModel.System.User.UserViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3 style="color: red">Are you sure want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dob)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Roles)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Roles)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-controller="User" method="post">
        <input type="hidden" asp-for="Id" />

        <input type="submit" value="Delete" class="btn btn-danger" />
        <br />
        <br />
        <a asp-action="GetAllUser" asp-controller="User">Back to List</a>
    </form>
</div>

eShopSolution.AdminApp/Views/User/Detail.cshtml
@model eShopSolution.ViewModel.System.User.UserViewModel

@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Detail</h1>

<div>
    <label style="color:red">@ViewBag.Error</label>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dob)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dob)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Roles)
        </dt>
        <dd class="col-sm-10">
            @foreach (var role in Model.Roles)
            {
                <span class="m-1">@role </span>
            }
        </dd>

    </dl>
</div>
<div>
    <form asp-action="Edit" asp-controller="User" method="get">
        <input name="UserId" type="hidden" value="@Model.Id" />
        <button class="btn btn-warning" style="text-decoration: none">
            Edit
        </button>

    </form>
    <br />
    <a asp-action="GetAllUser" asp-controller="User">Back to List</a>
</div>

eShopSolution.AdminApp/Views/User/Edit.cshtml
@model eShopSolution.ViewModel.System.User.UserViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="User" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden"/>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input readonly asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dob" class="control-label"></label>
                <input asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Roles" class="control-label"></label>
                <select name="Roles" class="form-control" multiple>
                    @{
                        var listRole = ViewBag.ListRole;
                    }
                    @{
                        var roleSelected = Model.Roles;
                    }
                    @foreach (var role in listRole)
                    {
                        if (roleSelected.Contains(role.Name))
                        {
                            <option value="@role.RoleId" selected>
                                @role.Name
                            </option>
                        }
                        else{
                         <option value="@role.RoleId">@role.Name</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAllUser" asp-controller="User">Back to List</a>
</div>

eShopSolution.AdminApp/Views/User/GetAllUser.cshtml
@using eShopSolution.ViewModel.Catalog.Common
@using eShopSolution.ViewModel.System.User
@using eShopSolution.ViewModel.Common
@model PageResult<UserViewModel>

@{
    ViewData["Title"] = "Manage User";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Manage Users</h1>
<form asp-action="GetAllUser" asp-controller="User" method="get">

    <div class="row">
        <div class="col-md-3  col-sm-12">
            <input type="text" name="Keyword" class="form-control" value="@ViewBag.txtLastSeachValue" placeholder="Enter Keyword">
        </div>
        <button class="btn btn-success">Search</button>

    </div>
</form>

<br />
<p>
    <a asp-action="Register" asp-controller="User" class="btn btn-primary">Create</a>
</p>
@if (Model.Items.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Username
                </th>
                <th>
                    PhoneNumber
                </th>
                <th>
                    FirstName
                </th>
                <th>
                    LastName
                </th>
                <th>
                    Dob
                </th>
                <th>
                    Roles
                </th>
                <th class="text-center">Setting</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dob)
                    </td>
                    <td>
                        @foreach (var role in item.Roles)
                        {
                            <label>@role</label>
                        }
                    </td>
                    <td class="text-center">

                        @Html.ActionLink("Edit", "Edit", new { UserId = item.Id }, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Detail", "Detail", new { UserId = item.Id }, new { @class = "btn btn-info" })
                        @Html.ActionLink("Delete", "Delete", new { UserId = item.Id }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3 class="d-flex justify-content-center align-items-center" style="color:red; font-weight:bold">Not Found</h3>
}

<div class="d-flex justify-content-center align-items-center">
    @await Component.InvokeAsync("Pager", Model)
</div>

<!-- #region notification -->
@if (ViewBag.SuccessMsg != null)
{
    <!-- Success notification -->
    <div style="position: absolute; top: 13%; right: 0; width:19%">
        <!-- Then put toasts within -->
        <div id="toast" role="alert" aria-live="assertive" aria-atomic="true" style="background-color: limegreen; border-radius:3px; border: 1px solid green">
            <div class="toast-header" style="color: green; display:flex; align-items:center; border:none">
                <i class="fa-solid fa-circle-check" style="height:5px; width:5px; display:flex; align-items:center; margin-right: 14px; color: green"></i>
                <strong class="mr-auto" style="color: green">Nofication</strong>
                <small class="text-muted" style="color: green">just now</small>
                <button id="btnCloseNotification" type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close" style="color: green">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body" style="background-color: azure">
                @ViewBag.SuccessMsg
            </div>
        </div>
    </div>
    <!-- END Success notification -->
}

@if (ViewBag.FailMsg != null)
{
    <!-- Error notification -->

    <div style="position: absolute; top: 13%; right: 0; width:19%">
        <!-- Then put toasts within -->
        <div id="toast" role="alert" aria-live="assertive" aria-atomic="true" style="background-color: indianred; border-radius:3px; border: 1px solid red">
            <div class="toast-header" style="color: red; display:flex; align-items:center; border:none">
                <i class="fa-solid fa-circle-check" style="height:5px; width:5px; display:flex; align-items:center; margin-right: 14px; color: red"></i>
                <strong class="mr-auto" style="color: red">Nofication</strong>
                <small class="text-muted" style="color: red">just now</small>
                <button id="btnCloseNotification" type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close" style="color: red">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body" style="background-color: azure">
                @ViewBag.FailMsg
            </div>
        </div>
    </div>

    <!-- END Error notification -->
}
<!-- #endregion -->
@section Scripts {
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $("#toast").fadeOut("slow");
            }, 3000);
        });

        $(document).ready(function () {
            $("#btnCloseNotification").click(function () {
                let parent = $(this).parent().parent().parent().hide();
            });
        });

    </script>

}

eShopSolution.AdminApp/Views/User/Register.cshtml
@model eShopSolution.ViewModel.System.User.RegisterUserRequest

@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Register</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <div>
            @if (ViewBag.Errors != null)
            {
                foreach (var error in ViewBag.Errors)
                {
                    <label style="color:red">@error</label>
                }
            }
          
        </div>
        <form asp-action="Register" asp-controller="User" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input type="password" asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dob" class="control-label"></label>
                <input type="date" asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Roles" class="control-label"></label>
                <select name="Roles" class="form-control" multiple>
                    @{
                        var listRole = ViewBag.ListRole;
                    }
                    @foreach(var role in listRole)
                    {
                        <option value="@role.RoleId">@role.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>